### --------------------------------------------------------------------------------------------------------------------
### Spring Config
### --------------------------------------------------------------------------------------------------------------------
spring:
    ai:
        openai:
            api-key: xxx
### --------------------------------------------------------------------------------------------------------------------
### App Config
### --------------------------------------------------------------------------------------------------------------------
app:
    dash-scope:
        api-key: xxx
        model: deepseek-r1
