### --------------------------------------------------------------------------------------------------------------------
### Spring Config
### --------------------------------------------------------------------------------------------------------------------
spring:
    ai:
        model:
            chat: deepseek
        deepseek:
            api-key: ${DEEPSEEK_API_KEY}
            chat:
                model: deepseek-v4-flash
### --------------------------------------------------------------------------------------------------------------------
### App Config
### --------------------------------------------------------------------------------------------------------------------
app:
    dash-scope:
        api-key: ${DEEPSEEK_API_KEY}
        model: deepseek-v4-flash
